version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      gradle-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      gha-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7
