name: Create or update release notes PR

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upset_release_notes_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # needed to be able to resolve commit of previous version
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Download release-note tool
        run: GO111MODULE=on go get k8s.io/release/cmd/release-notes@v0.7.0

      - name: create or update release note PR
        env:
          # Required for the `hub` CLI
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./hack/create_or_update_release_notes_pr.sh
